name: complex-numbers
version: 1.0.0.1

dependencies:
  - base

library:
  exposed-modules: ComplexNumbers
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - complex-numbers
      - hspec
