name: nth-prime
version: 2.1.0.5

dependencies:
  - base

library:
  exposed-modules: Prime
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - nth-prime
      - hspec
