name: change

dependencies:
  - base

library:
  exposed-modules: Change
  source-dirs: src
  dependencies:
    - containers
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - change
      - hspec
