name: not-my-type
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: NotMyType
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - not-my-type
      - hspec
