name: isbn-verifier
version: 1.1.0.1

dependencies:
  - base

library:
  exposed-modules: IsbnVerifier
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isbn-verifier
      - hspec
