name: parallel-letter-frequency

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: Frequency
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
    - parallel

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - parallel-letter-frequency
      - hspec
