name: raindrops

dependencies:
  - base
  - text

library:
  exposed-modules: Raindrops
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - raindrops
      - hspec
