name: resistor-color-trio

dependencies:
  - base
  - text

library:
  exposed-modules: ResistorColors
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - resistor-color-trio
      - hspec
