name: twelve-days
version: 1.2.0.5

dependencies:
  - base

library:
  exposed-modules: TwelveDays
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - twelve-days
      - hspec
