name: variable-length-quantity
version: 0.0.0.1 # TODO: what should this number be?

dependencies:
  - base

library:
  exposed-modules: Vlq
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - mtl

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - variable-length-quantity
      - hspec
      - text
      - QuickCheck
