name: armstrong-numbers

dependencies:
  - base

library:
  exposed-modules: ArmstrongNumbers
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - armstrong-numbers
      - hspec
