name: food-chain

dependencies:
  - base

library:
  exposed-modules: FoodChain
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
    - array

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - food-chain
      - HUnit
