name: binary-search

dependencies:
  - base
  - array

library:
  exposed-modules: BinarySearch
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary-search
      - hspec
