name: language-list
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: LanguageList
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - language-list
      - hspec
