name: exercism-clock
version: 2.3.0.7

dependencies:
  - base

library:
  exposed-modules: Clock
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - exercism-clock
      - hspec
