name: zebra-puzzle
version: 1.1.0.5

dependencies:
  - base

library:
  exposed-modules: ZebraPuzzle
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - zebra-puzzle
      - hspec
