name: robot-simulator
version: 3.1.0.7

dependencies:
  - base

library:
  exposed-modules: Robot
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - robot-simulator
      - hspec
