name: anagram
version: 1.4.0.8

dependencies:
  - base

library:
  exposed-modules: Anagram
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - anagram
      - hspec
