# Changing an example's package.yaml should cause a cache miss on the main key,
# but there should be a hit on a restore key.
name: accumulate

dependencies:
  - base

library:
  exposed-modules: Accumulate
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - accumulate
      - hspec
