name: rotational-cipher
version: 1.2.0.2

dependencies:
  - base

library:
  exposed-modules: RotationalCipher
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rotational-cipher
      - hspec
