name: pangram

dependencies:
  - base
  - text
  - containers

library:
  exposed-modules: Pangram
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pangram
      - hspec
