name: isogram

dependencies:
  - base
  - containers
  - text
  - mono-traversable

library:
  exposed-modules: Isogram
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - isogram
      - hspec
