name: proverb
version: 1.1.0.2

dependencies:
  - base

library:
  exposed-modules: Proverb
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - proverb
      - hspec
