name: temperature
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: Temperature
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - temperature
      - hspec
