name: pacman-rules
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: PacmanRules
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pacman-rules
      - hspec
