name: go-counting

dependencies:
  - base
  - containers

library:
  exposed-modules: Counting
  source-dirs: src
  dependencies:
    - array

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - go-counting
      - hspec
