name: etl

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: ETL
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - etl
      - hspec
