name: complex-numbers

dependencies:
  - base

library:
  exposed-modules: ComplexNumbers
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - complex-numbers
      - hspec
