name: kindergarten-garden
version: 1.1.1.7

dependencies:
  - base

library:
  exposed-modules: Garden
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - kindergarten-garden
      - hspec
