name: pov

library:
  exposed-modules: POV
  source-dirs: src
  dependencies:
    - base
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pov
      - test-prelude
      - containers
