name: lucians-luscious-lasagna
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: LuciansLusciousLasagna
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - lucians-luscious-lasagna
      - hspec
