name: perfect-numbers

dependencies:
  - base

library:
  exposed-modules: PerfectNumbers
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - perfect-numbers
      - hspec
