name: diamond

dependencies:
  - base

library:
  exposed-modules: Diamond
  source-dirs: src
  dependencies:
    - text

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - diamond
      - hspec
      - QuickCheck
      - string-conversions
