name: gigasecond

dependencies:
  - base
  - time

library:
  exposed-modules: Gigasecond
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - gigasecond
      - hspec
