name: largest-series-product

dependencies:
  - base

library:
  exposed-modules: Series
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - largest-series-product
      - hspec
