name: sum-of-multiples
version: 1.5.0.10

dependencies:
  - base

library:
  exposed-modules: SumOfMultiples
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sum-of-multiples
      - hspec
