name: list-ops
version: 2.3.0.5

dependencies:
  - base

library:
  exposed-modules: ListOps
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - list-ops
      - hspec
