name: luhn
version: 1.3.0.5

dependencies:
  - base

library:
  exposed-modules: Luhn
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - luhn
      - hspec
