name: nucleotide-count
version: 1.3.0.6

dependencies:
  - base
  - containers

library:
  exposed-modules: DNA
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - nucleotide-count
      - hspec
