name: exercism-clock

dependencies:
  - base

library:
  exposed-modules: Clock
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - exercism-clock
      - hspec
