name: all-your-base
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: Base
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - all-your-base
      - hspec
