name: kitchen-calculator
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: KitchenCalculator
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - kitchen-calculator
      - hspec
