name: transpose

dependencies:
  - base

library:
  exposed-modules: Transpose
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - transpose
      - hspec
