name: binary
version: 0.9.0.2 # 2016-07-26

dependencies:
  - base

library:
  exposed-modules: Binary
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - binary
      - hspec
