name: bob

dependencies:
  - base

library:
  exposed-modules: Bob
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bob
      - aeson
      - bytestring
      - hspec
      - HUnit
