name: bettys-bike-shop
version: 1.0.0.0

dependencies:
  - base
  - ToString

library:
  exposed-modules: 
    - BettysBikeShop
    - ToString
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bettys-bike-shop
      - ToString
      - hspec
