name: bettys-bike-shop
version: 1.0.0.0

dependencies:
  - base


library:
  exposed-modules: 
    - BettysBikeShop

  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bettys-bike-shop
      - hspec
