name: lens-person
version: 0.1.0.2

dependencies:
  - base
  - time

library:
  exposed-modules: Person
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - lens-person
      - hspec
