name: acronym

dependencies:
  - base

library:
  exposed-modules: Acronym
  source-dirs: src
  dependencies:

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - acronym
      - hspec
