name: forth

dependencies:
  - base
  - text

library:
  exposed-modules: Forth
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
    - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - forth
      - HUnit
