name: forth
version: 1.2.0.4

dependencies:
  - base
  - text

library:
  exposed-modules: Forth
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - forth
      - hspec
