name: collatz-conjecture

dependencies:
  - base

library:
  exposed-modules: CollatzConjecture
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - collatz-conjecture
      - hspec
