name: resistor-color-duo

dependencies:
  - base

library:
  exposed-modules: ResistorColors
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - resistor-color-duo
      - hspec
