name: rail-fence-cipher

dependencies:
  - base

library:
  exposed-modules: RailFenceCipher
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rail-fence-cipher
      - hspec
