name: rna-transcription
version: 1.3.0.8

dependencies:
  - base

library:
  exposed-modules: DNA
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rna-transcription
      - hspec
