name: lens-person

dependencies:
  - base
  - time

library:
  exposed-modules: Person
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - lens-person
      - hspec
