name: parallel-letter-frequency

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: Frequency
  source-dirs: src
  dependencies:
    - parallel

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - parallel-letter-frequency
      - hspec

benchmarks:
  bench:
    ghc-options: -threaded -with-rtsopts=-N -O2

    main: Benchmark.hs
    source-dirs: bench
    dependencies:
      - parallel-letter-frequency
      - criterion
