name: pov
version: 1.1.1.4

library:
  exposed-modules: POV
  source-dirs: src
  dependencies:
    - base
    - containers
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - pov
      - test-prelude
      - containers
