name: reverse-string

dependencies:
  - base

library:
  exposed-modules: ReverseString
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - reverse-string
      - hspec
