name: rational-numbers

dependencies:
  - base

library:
  exposed-modules: RationalNumbers
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - rational-numbers
      - hspec
