name: sgf-parsing
version: 0.1.0.2

dependencies:
  - base
  - containers
  - text

library:
  exposed-modules: Sgf
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - sgf-parsing
      - hspec
