name: alphametics
version: 1.2.0.4

dependencies:
  - base

library:
  exposed-modules: Alphametics
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - alphametics
      - hspec
