name: poker
version: 1.1.1.0

dependencies:
  - base

library:
  exposed-modules: Poker
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - poker
      - hspec
