name: bracket-push
version: 1.3.0.4

dependencies:
  - base

library:
  exposed-modules: Brackets
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bracket-push
      - hspec
