name: atbash-cipher

dependencies:
  - base

library:
  exposed-modules: Atbash
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.
    - split

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - atbash-cipher
      - hspec
