name: affine-cipher

dependencies:
  - base

library:
  exposed-modules: Affine
  source-dirs: src
  dependencies:
    - text

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - affine-cipher
      - hspec
