name: zipper
version: 1.1.0.4

dependencies:
  - base

library:
  exposed-modules: Zipper
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - zipper
      - hspec
