name: word-search

dependencies:
  - base

library:
  exposed-modules: WordSearch
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - word-search
      - hspec
