name: twelve-days

dependencies:
  - base

library:
  exposed-modules: TwelveDays
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - twelve-days
      - hspec
