name: book-store
version: 1.0.0.0

dependencies:
  - base
  
library:
  exposed-modules: BookStore
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - book-store
      - hspec
