name: perfect-numbers
version: 1.1.0.3

dependencies:
  - base

library:
  exposed-modules: PerfectNumbers
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - perfect-numbers
      - hspec
