name: spiral-matrix
version: 1.0.0.1

dependencies:
  - base

library:
  exposed-modules: Spiral
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - spiral-matrix
      - hspec
