name: spiral-matrix
version: 1.1.0.3

dependencies:
  - base

library:
  exposed-modules: Spiral
  source-dirs: src
  ghc-options: -Wall
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - spiral-matrix
      - hspec
