name: octal

dependencies:
  - base

library:
  exposed-modules: Octal
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - octal
      - hspec
      - QuickCheck
