name: leap
version: 1.3.0.6

dependencies:
  - base

library:
  exposed-modules: LeapYear
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - leap
      - hspec
