name: collatz-conjecture
version: 1.1.1.1

dependencies:
  - base

library:
  exposed-modules: CollatzConjecture
  source-dirs: src
  dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - collatz-conjecture
      - hspec
