name: matrix
version: 1.0.0.5

dependencies:
  - base
  - vector

library:
  exposed-modules: Matrix
  source-dirs: src
  # dependencies:
  # - foo       # List here the packages you
  # - bar       # want to use in your solution.

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - matrix
      - hspec
