#!/usr/bin/env bash

programName=`basename "$0"`
dependencies="`dirname ${BASH_SOURCE}`/dependencies.txt"
example="example.hs"
testSuffix="_test.hs"

getDependencies () {
  (
    for pattern in "$@"; do
      grep "${pattern}" "${dependencies}" | cut -d: -f2 | xargs -n1
    done
  ) | sort -u
}

exampleDependencies () {
  (
    for exercise in "$@"; do
      getDependencies "${exercise}/${example}"
    done
  ) | sort -u
}

testDependencies () {
  (
    for exercise in "$@"; do
      getDependencies "${exercise}/${exercise}${testSuffix}"
    done
  ) | sort -u
}

selectedDependencies () {
  comm ${commArgs} --output-delimiter " " \
       <(exampleDependencies "$@")        \
       <(testDependencies "$@") | xargs -n1
}

eval set -- `getopt -o "" --long file:,examples,tests,only-in-examples,only-in-tests,examples-and-tests,examples-xor-tests -n ${programName} -- "$@"`

commArgs=""

while true ; do
    case "$1" in
        --examples          ) commArgs="-2"           ; shift            ;;
        --tests             ) commArgs="-1"           ; shift            ;;
        --only-in-examples  ) commArgs="-23"          ; shift            ;;
        --only-in-tests     ) commArgs="-13"          ; shift            ;;
        --examples-and-tests) commArgs="-12"          ; shift            ;;
        --examples-xor-tests) commArgs="-3"           ; shift            ;;
        --file              ) case "$2" in
                                  "")                   shift 2          ;;
                                  * ) dependencies=$2 ; shift 2          ;;
                              esac ;;
        --                  )                           shift   ; break  ;;
        *) echo "$0: Unexpected error using getopt."            ; exit 1 ;;
    esac
done

selectedDependencies "$@"
